.MODEL SMALL
.STACK 100H

.DATA
    PASSWORD DB '5'          ; CORRECT PASSWORD
    ATTEMPTS DB 3            ; MAX ATTEMTS

    MSG1 DB 13,10,'ENTER PASSWORD: $'
    MSG2 DB 13,10,'ACCESS GRANTED$'
    MSG3 DB 13,10,'WRONG PASSWORD$'
    MSG4 DB 13,10,'ATTEMPTS LEFT: $'
    MSG5 DB 13,10,'ACCESS DENIED$'

.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
       
   

START:

    ; DISPLAY ENTER PASSWORD
    
    LEA DX,MSG1
    MOV AH,09H
    INT 21H

 
    MOV AH,01H
    INT 21H

   
    CMP AL,PASSWORD
    JE CORRECT

    ; DISPLAY WRONG PASSWORD 
    
    LEA DX,MSG3
    MOV AH,09H
    INT 21H

    ;DECREASE ATTEMPT 
    
    DEC ATTEMPTS

    ;CHECK IF ATTEMTS == 0  THEN IT WILL SHOW ACCESS DENIED
     
    CMP ATTEMPTS,0
    JZ DENIED

    ; IT SHOWS ATTEMPTS LEFT
    
    LEA DX,MSG4
    MOV AH,09H
    INT 21H
    
    MOV DL,ATTEMPTS
    ADD DL,'0'
    MOV AH,02H
    INT 21H

    JMP START

CORRECT:
    LEA DX,MSG2
    MOV AH,09H
    INT 21H
    JMP EXIT

DENIED:
    LEA DX,MSG5
    MOV AH,09H
    INT 21H

EXIT:
    MOV AH,4CH
    INT 21H

MAIN ENDP
END MAIN